{
 "title": "Nginx",
 "tags": [
  "nginx",
  "web"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(nginx_up, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "nginx_up{instance=~\"$instance.*\"}"
    }
   ]
  },
  {
   "title": "Requests total",
   "type": "graph",
   "description": "Общее количество клиентских запросов, измеренное за последние 5 минут, за временной ряд в векторе диапазона",
   "gridPos": { "h": 8, "w": 10, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(nginx_http_requests_total[5m])",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Handled connections",
   "type": "graph",
   "description": "Общее количество обработанных соединений, измеренное за последние 5 минут, за временной ряд в векторе диапазона",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(nginx_connections_handled[5m])",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "graph",
   "description": "Текущее количество активных клиентских подключений, включая Waiting подключения",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nginx_connections_active", "legendFormat": "Count" }
   ]
  },
  {
   "title": "Waiting connections",
   "type": "graph",
   "description": "Текущее число незанятых клиентских подключений, ожидающих запроса",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nginx_connections_waiting", "legendFormat": "Count" }
   ]
  },
  {
   "title": "Reading connections",
   "type": "graph",
   "description": "Текущее количество соединений, где nginx читает заголовок запроса",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nginx_connections_reading", "legendFormat": "Count" }
   ]
  },
  {
   "title": "Writing connections",
   "type": "graph",
   "description": "Текущее число соединений, где nginx записывает ответ клиенту",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nginx_connections_writing", "legendFormat": "Count" }
   ]
  }
 ]
}